###Create Payment
POST http://localhost:3000/payment/ HTTP/1.1
Content-Type: application/json

{
"name":"Subat ödeme",
"amount": 555,
"receiver": "Me",
"studentId":6
}
###Update Payment
PATCH  http://localhost:3000/payment/1 HTTP/1.1
Content-Type: application/json

{
"amount": 1,
"receiver": "me",
"studentId":1
}
### Delete Paymentby ID
DELETE http://localhost:3000/payment/3 HTTP/1.1
### Get Payment By ID
GET http://localhost:3000/payment/3  HTTP/1.1
### receiver query
GET http://localhost:3000/payment?receiver=AAAAA HTTP/1.1
### studentid query
GET http://localhost:3000/payment?studentId=4 HTTP/1.1