###Create student
POST http://localhost:3000/student/signup HTTP/1.1
Content-Type: application/json

{
"name": "jeli",
"surname": "keli",
"phone": "12345",
"guardian_name": "Kirk",
"guardian_surname": "Elli bir",
"guardian_phone": "1111",
"address": "iznik bursa",
"school": "Kılıcaslan ",
"grade": 5,
"lectures": "Robotik kodlama, İngilizce",
"info": "Kardeside burada"
}
### Get Student By ID
GET http://localhost:3000/student/2    HTTP/1.1
### Name query
GET http://localhost:3000/student?name=jeli&surname=keli  HTTP/1.1
### Just name
GET http://localhost:3000/student?name=deli&  HTTP/1.1
### Just surname
GET http://localhost:3000/student?surname=veli  HTTP/1.1
### guardian name surname

GET http://localhost:3000/student?guardian_surname=Elli bir  HTTP/1.1
### phone query
GET http://localhost:3000/student?phone=12345  HTTP/1.1
### guardian phone query
GET http://localhost:3000/student?guardian_phone=111  HTTP/1.1
### school query
GET http://localhost:3000/student?school=selcuk    HTTP/1.1

