###Create student
POST http://localhost:3000/student/signup HTTP/1.1
Content-Type: application/json

{
"name": "ABC",
"surname": "BBB",
"phone": "12345",
"guardian_name": "CCCC",
"guardian_surname": "DDD bir",
"guardian_phone": "1111",
"address": "FFFFF BURSA",
"school": "Alpaslan",
"grade": 5,
"lectures": "Matematik",
"info": "Kardeside burada"
}
### Get Student By ID
GET http://localhost:3000/student/2    HTTP/1.1
### Empty query
GET http://localhost:3000/student/all  HTTP/1.1
### Name query
GET http://localhost:3000/student?name=jeli&surname=keli  HTTP/1.1
### Just name
GET http://localhost:3000/student?name=ABC   HTTP/1.1
### Just surname
GET http://localhost:3000/student?surname=veli  HTTP/1.1
### guardian name surname

GET http://localhost:3000/student?guardian_surname=Elli bir  HTTP/1.1
### phone query
GET http://localhost:3000/student?phone=12345  HTTP/1.1
### guardian phone query
GET http://localhost:3000/student?guardian_phone=111  HTTP/1.1
### school query
GET http://localhost:3000/student?school=Alpaslan  HTTP/1.1
### lectures query
GET http://localhost:3000/student?lectures=Robotik    HTTP/1.1
### lectures query
GET http://localhost:3000/student?lectures=Matematik    HTTP/1.1



